#!/bin/bash
echo "=== MEDGUARD360 INTEGRATION STATUS ==="
echo ""
echo "Auth:"
grep CLERK_SECRET_KEY /opt/medguard360/.env | grep -q PLACEHOLDER && echo "  ⚠️  Clerk: Harness mode (add real key)" || echo "  ✅ Clerk: Production"
echo ""
echo "Communications:"
grep TWILIO_ACCOUNT_SID /opt/medguard360/.env | grep -q PLACEHOLDER && echo "  ⚠️  Twilio: Harness mode (add real key)" || echo "  ✅ Twilio: Production"
grep FCM_PROJECT_ID /opt/medguard360/.env | grep -q PLACEHOLDER && echo "  ⚠️  FCM: Harness mode (add real key)" || echo "  ✅ FCM: Production"
echo ""
echo "Claims:"
grep CLEARINGHOUSE_API_KEY /opt/medguard360/.env | grep -q PLACEHOLDER && echo "  ⚠️  Clearinghouse: Harness mode (add real key)" || echo "  ✅ Clearinghouse: Production"
echo ""
echo "Biometrics:"
grep SUPREMA_API_KEY /opt/medguard360/.env | grep -q PLACEHOLDER && echo "  ⚠️  Suprema: Harness mode (add real key)" || echo "  ✅ Suprema: Production"
grep NEC_API_KEY /opt/medguard360/.env | grep -q PLACEHOLDER && echo "  ⚠️  NEC: Harness mode (add real key)" || echo "  ✅ NEC: Production"
echo ""
echo "=== TO ENABLE PRODUCTION ==="
echo "1. Edit /opt/medguard360/.env"
echo "2. Replace PLACEHOLDER values with real credentials"
echo "3. Run: /opt/medguard360/deploy/update.sh"
