/**
 * Data access layer for notification_templates and notification_logs tables.
 *
 * notification_templates — seeded at migration time; read-only at runtime.
 * notification_logs      — append-only audit trail of every delivery attempt.
 */

import { query } from '@medguard360/shared';
import { NotificationTemplateRow, NotificationLogRow } from './types';

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

/**
 * Find an active notification template by its unique key.
 * Returns null if the template does not exist or is inactive.
 */
export async function getTemplate(key: string): Promise<NotificationTemplateRow | null> {
  const r = await query<NotificationTemplateRow>(
    'notification.getTemplate',
    `SELECT id, template_key, channel, subject, body_template, is_active, created_at
     FROM notification_templates
     WHERE template_key = $1 AND is_active = true
     LIMIT 1`,
    [key],
  );
  return r.rows[0] ?? null;
}

// ---------------------------------------------------------------------------
// Notification logs
// ---------------------------------------------------------------------------

/**
 * Insert a row into notification_logs.
 * Pass the full or partial log shape — id and sent_at are generated by Postgres.
 */
export async function logNotification(
  data: Omit<Partial<NotificationLogRow>, 'id' | 'sent_at'> & {
    channel: 'email' | 'sms' | 'push';
    body: string;
  },
): Promise<NotificationLogRow> {
  const r = await query<NotificationLogRow>(
    'notification.logNotification',
    `INSERT INTO notification_logs
       (recipient_user_id, channel, template_key, subject, body,
        status, vendor_message_id, error_message)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
     RETURNING *`,
    [
      data.recipient_user_id ?? null,
      data.channel,
      data.template_key ?? null,
      data.subject ?? null,
      data.body,
      data.status ?? 'sent',
      data.vendor_message_id ?? null,
      data.error_message ?? null,
    ],
  );
  return r.rows[0];
}

/**
 * Retrieve recent notification log entries.
 * Supports optional filtering by recipient_user_id, channel, and status.
 */
export async function listLogs(filters: {
  recipientUserId?: string;
  channel?: string;
  status?: string;
  limit?: number;
}): Promise<NotificationLogRow[]> {
  const conditions: string[] = [];
  const params: unknown[] = [];
  let idx = 1;

  if (filters.recipientUserId) {
    conditions.push(`recipient_user_id = $${idx++}`);
    params.push(filters.recipientUserId);
  }
  if (filters.channel) {
    conditions.push(`channel = $${idx++}`);
    params.push(filters.channel);
  }
  if (filters.status) {
    conditions.push(`status = $${idx++}`);
    params.push(filters.status);
  }

  const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
  const limit = filters.limit ?? 100;
  params.push(limit);

  const r = await query<NotificationLogRow>(
    'notification.listLogs',
    `SELECT * FROM notification_logs ${where} ORDER BY sent_at DESC LIMIT $${idx}`,
    params,
  );
  return r.rows;
}
