/**
 * hie-service domain types.
 *
 * Covers FHIR R4 resource persistence shapes and referral domain objects.
 * These are the internal DB/API shapes — see fhir.ts for FHIR wire format builders.
 */

// ---------------------------------------------------------------------------
// FHIR resource store
// ---------------------------------------------------------------------------

/** Resource types we persist from inbound/outbound HIE traffic. */
export type FhirResourceType =
  | 'Patient'
  | 'Encounter'
  | 'Observation'
  | 'Condition'
  | 'MedicationRequest'
  | 'ServiceRequest'
  | 'Consent';

/** Row shape for the fhir_resources table. */
export interface FhirResourceRow {
  id: string;
  resource_type: FhirResourceType;
  fhir_id: string;
  patient_id: string | null;
  state_code: string;
  resource_data: Record<string, unknown>;
  source_system: string | null;
  created_at: string;
  updated_at: string;
}

/** Input for saving a FHIR resource (id is generated by DB). */
export interface SaveFhirResourceInput {
  resource_type: FhirResourceType;
  fhir_id: string;
  patient_id?: string | null;
  state_code: string;
  resource_data: Record<string, unknown>;
  source_system?: string | null;
}

/** Filters for listing FHIR resources. */
export interface FhirResourceFilters {
  patientId?: string;
  resourceType?: FhirResourceType;
}

// ---------------------------------------------------------------------------
// Referral
// ---------------------------------------------------------------------------

/** Priority levels for a referral (mirrors FHIR ServiceRequest.priority). */
export type ReferralPriority = 'stat' | 'urgent' | 'routine' | 'elective';

/** Lifecycle states for a referral. */
export type ReferralStatus =
  | 'pending'
  | 'accepted'
  | 'completed'
  | 'declined'
  | 'cancelled';

/** Row shape for the referrals table. */
export interface ReferralRow {
  id: string;
  from_provider_id: string;
  to_provider_id: string | null;
  patient_id: string;
  state_code: string;
  reason: string;
  priority: ReferralPriority;
  status: ReferralStatus;
  fhir_service_request_id: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  created_by: string;
}

/** Input for creating a new referral (status defaults to 'pending'). */
export interface CreateReferralInput {
  id?: string;  // optional pre-generated UUID; DB generates one if omitted
  from_provider_id: string;
  to_provider_id?: string | null;
  patient_id: string;
  state_code: string;
  reason: string;
  priority: ReferralPriority;
  fhir_service_request_id?: string | null;
  notes?: string | null;
  created_by: string;
}

/** Input for updating referral status and optional notes. */
export interface UpdateReferralInput {
  status: ReferralStatus;
  notes?: string | null;
}

/** Filters for listing referrals. */
export interface ReferralFilters {
  fromProviderId?: string;
  toProviderId?: string;
  patientId?: string;
  status?: ReferralStatus;
}

// ---------------------------------------------------------------------------
// Consent (42 CFR Part 2 / HIPAA scopes)
// ---------------------------------------------------------------------------

/** Row shape for the hie_consents table. */
export interface ConsentRow {
  id: string;
  patient_id: string;
  scope: string;
  granted_to_org: string;
  effective_from: string;
  effective_to: string | null;
  status: string;
  fhir_resource_id: string | null;
  created_at: string;
  updated_at: string;
}

/** Input for recording a new patient consent. */
export interface CreateConsentInput {
  patient_id: string;
  scope: string;
  granted_to_org: string;
  effective_from: string;
  effective_to?: string | null;
  fhir_resource_id?: string | null;
}

// ---------------------------------------------------------------------------
// Shared
// ---------------------------------------------------------------------------

/** Paginated list wrapper. */
export interface ListResult<T> {
  count: number;
  items: T[];
}
